### ISSUE TITLE
distance & blend_eeps

### ISSUE THREAD

**Issue by jieunchoi** [aarondotter/iso#4]
removing distance from EEPs needs to be propagated to blend_eeps:

  blending            2  tracks:
00030M_PT.track                 00030M_tau100.track  
   0.0000000000000000        1.0000000000000000       =>    1.0000000000000000  
At line 118 of file /n/home07/jieunchoi/iso/src/blend_eeps.f90
Fortran runtime error: Index '1' of dimension 1 of array 's_old%dist' above upper bound of 0

**Comment by aarondotter** [comment]
fixed with commit 48cfb08664f68554313ccf19a19d9d689731f001
