### ISSUE TITLE
phase = 6 identification

### ISSUE THREAD

**Issue by jieunchoi** [aarondotter/iso#5]
For certain masses (e.g., 6.4 Msun shown below), the WDCS gets tagged as the WR phase:

<img width="598" alt="screen shot 2016-01-20 at 14 32 30" src="https://cloud.githubusercontent.com/assets/4583333/12460647/ba132368-bf82-11e5-8038-b411f22d7186.png">

red = phase 6 (postAGB)
blue = phase 9 (WR)

Maybe we should set a minimum mass for the WR phase to occur (can be the same as min_for_high_mass_star = 10.0 !Msun in input.nml) and prohibit the phase from being tagged != 6 for the subsequent points in the track once an EEP point is flagged as phase=6?

**Comment by aarondotter** [comment]
I've attempted a fix for this by using the high-mass / low-mass stellar type to distinguish.  Check it out and see if that solves your problem.  Will leave the issue open until it's settled.

**Comment by jieunchoi** [comment]
Forgot to update, but this has been fixed!
